version: '2'

networks:
    public:
        driver: bridge
    private:
        driver: bridge

services:
  php-fpm:
    container_name: php-container-fpm
    build:
      context: .
      dockerfile: ./images/php-7.0-fpm
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - INSTALL_MCRYPT=${INSTALL_MCRYPT}
        - INSTALL_PDO_MYSQL=${INSTALL_PDO_MYSQL}
        - INSTALL_PDO_PGSQL=${INSTALL_PDO_PGSQL}
        - INSTALL_ICONV=${INSTALL_ICONV}
        - INSTALL_SOAP=${INSTALL_SOAP}
        - XDEBUG_CONFIG_FILE=${XDEBUG_CONFIG_FILE}
    networks:
      - private
    env_file: ${ENV_FILE}

  php-cli:
    container_name: php-container-cli
    build:
      context: .
      dockerfile: ./images/php-7.0-cli
      args:
        - INSTALL_XDEBUG=${CLI_INSTALL_XDEBUG}
        - INSTALL_MCRYPT=${CLI_INSTALL_MCRYPT}
        - INSTALL_PDO_MYSQL=${CLI_INSTALL_PDO_MYSQL}
        - INSTALL_PDO_PGSQL=${CLI_INSTALL_PDO_PGSQL}
        - INSTALL_ICONV=${CLI_INSTALL_ICONV}
        - INSTALL_SOAP=${CLI_INSTALL_SOAP}
        - XDEBUG_CONFIG_FILE=${CLI_XDEBUG_CONFIG_FILE}
    networks:
      - private
    env_file: ${ENV_FILE}

  nginx:
    container_name: nginx-container
    image: ${NGINX_DOCKER_IMAGE_VENDOR}:${NGINX_DOCKER_IMAGE_TAG}
    ports:
      - "${NGINX_HOST_PORT}:80"
    networks:
      - public
      - private
    env_file: ${ENV_FILE}

  mysql:
    container_name: mysql-container
    image: ${MYSQL_DOCKER_IMAGE_VENDOR}:${MYSQL_DOCKER_IMAGE_TAG}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    networks:
      - private
    env_file: ${ENV_FILE}

  memcached:
    container_name: memcached-container
    image: ${MEMCACHED_DOCKER_IMAGE_VENDOR}:${MEMCACHED_DOCKER_IMAGE_TAG}
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    networks:
      - private
    env_file: ${ENV_FILE}





