version: '2'

networks:
    public:
        driver: bridge
    private:
        driver: bridge

services:
  php:
    container_name: php-container
    image: ${PHP_DOCKER_IMAGE_VENDOR}:${PHP_DOCKER_IMAGE_TAG}
    volumes:
      - ${WWW_ROOT}:/var/www/html
      - ${PHP_CONFIG_ROOT}:/usr/local/etc/php
    networks:
      - private
    env_file: ${ENV_FILE}

  nginx:
    container_name: nginx-container
    image: ${NGINX_DOCKER_IMAGE_VENDOR}:${NGINX_DOCKER_IMAGE_TAG}
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ${WWW_ROOT}:/var/www/html
      - ${NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_VHOST_ROOT}:/etc/nginx/sites-available
      - ${NGINX_LOG_ROOT}:/var/log/nginx
    networks:
      - public
      - private
    env_file: ${ENV_FILE}

  mysql:
    container_name: mysql-container
    image: ${MYSQL_DOCKER_IMAGE_VENDOR}:${MYSQL_DOCKER_IMAGE_TAG}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ./app/conf/mysql:/etc/mysql/conf.d
      - ./app/logs/mysql:/var/logs/mysql/
    networks:
      - private
    env_file: ${ENV_FILE}

  memcached:
    container_name: memcached-container
    image: ${MEMCACHED_DOCKER_IMAGE_VENDOR}:${MEMCACHED_DOCKER_IMAGE_TAG}
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    networks:
      - private
    env_file: ${ENV_FILE}